# Generated by Django 5.0.3 on 2024-08-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_registration_review_payment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='booked', max_length=50),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
